theme: jekyll-theme-minimal
title: Data Science Projects
logo_url: /images/DSC_1008.JPG
author: Anastasia Kiiru
email: kiiru.anastasia@gmail.com
description: The page contains all Data Science projects I've done

#social links
twitter_username: AnastasiaKiiru
github_username: Kiiru-Anastasia

show_excerpts: true
